-- Enhanced Order Dispatch System Database (150+ Columns)
CREATE DATABASE IF NOT EXISTS order_dispatch_db;
USE order_dispatch_db;

CREATE TABLE IF NOT EXISTS orders (
    -- Primary Identification (5 columns)
    order_id VARCHAR(50) PRIMARY KEY,
    reference_number VARCHAR(50),
    po_number VARCHAR(50),
    invoice_number VARCHAR(50),
    external_order_id VARCHAR(100),
    
    -- Customer Information (15 columns)
    customer_id VARCHAR(50) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    customer_email VARCHAR(100),
    customer_phone VARCHAR(20),
    customer_mobile VARCHAR(20),
    customer_fax VARCHAR(20),
    customer_company VARCHAR(150),
    customer_tax_id VARCHAR(50),
    customer_type VARCHAR(30),
    customer_segment VARCHAR(50),
    customer_tier VARCHAR(20),
    customer_since DATE,
    customer_rating DECIMAL(3,2),
    customer_lifetime_value DECIMAL(12,2),
    account_manager VARCHAR(100),
    
    -- Order Date/Time Information (10 columns)
    order_date DATE NOT NULL,
    order_time TIME,
    order_datetime DATETIME,
    order_timezone VARCHAR(50),
    expected_ship_date DATE,
    requested_delivery_date DATE,
    promised_delivery_date DATE,
    actual_ship_date DATE,
    actual_delivery_date DATE,
    order_processing_time INT,
    
    -- Order Status & Priority (10 columns)
    order_status VARCHAR(30) DEFAULT 'Pending',
    order_substatus VARCHAR(50),
    priority_level VARCHAR(20) DEFAULT 'Medium',
    priority_score INT,
    urgency_flag BOOLEAN DEFAULT FALSE,
    rush_order BOOLEAN DEFAULT FALSE,
    backorder_status VARCHAR(30),
    fulfillment_status VARCHAR(30),
    approval_status VARCHAR(30),
    cancellation_reason TEXT,
    
    -- Order Classification (10 columns)
    order_type VARCHAR(50),
    order_category VARCHAR(50),
    order_source VARCHAR(50),
    sales_channel VARCHAR(50),
    sales_rep VARCHAR(100),
    sales_team VARCHAR(100),
    department VARCHAR(50),
    division VARCHAR(50),
    territory VARCHAR(50),
    region VARCHAR(50),
    
    -- Marketing & Promotion (8 columns)
    marketing_campaign VARCHAR(150),
    campaign_id VARCHAR(50),
    promo_code VARCHAR(50),
    discount_code VARCHAR(50),
    affiliate_id VARCHAR(50),
    referral_source VARCHAR(100),
    utm_source VARCHAR(100),
    utm_campaign VARCHAR(100),
    
    -- Product Information (20 columns)
    product_id VARCHAR(50),
    product_name VARCHAR(200),
    product_category VARCHAR(100),
    product_subcategory VARCHAR(100),
    product_line VARCHAR(100),
    brand VARCHAR(100),
    model VARCHAR(100),
    sku VARCHAR(100),
    upc VARCHAR(50),
    ean VARCHAR(50),
    isbn VARCHAR(50),
    manufacturer VARCHAR(100),
    manufacturer_part_number VARCHAR(100),
    supplier_id VARCHAR(50),
    supplier_name VARCHAR(100),
    product_description TEXT,
    product_weight DECIMAL(10,3),
    product_dimensions VARCHAR(50),
    product_color VARCHAR(50),
    product_size VARCHAR(50),
    
    -- Inventory & Stock (12 columns)
    quantity INT DEFAULT 1,
    quantity_shipped INT DEFAULT 0,
    quantity_backordered INT DEFAULT 0,
    quantity_cancelled INT DEFAULT 0,
    stock_location VARCHAR(100),
    bin_location VARCHAR(50),
    lot_number VARCHAR(50),
    serial_number VARCHAR(100),
    batch_number VARCHAR(100),
    expiry_date DATE,
    manufacture_date DATE,
    reorder_point INT,
    
    -- Pricing & Financial (25 columns)
    unit_price DECIMAL(12,2) DEFAULT 0.00,
    list_price DECIMAL(12,2) DEFAULT 0.00,
    cost_price DECIMAL(12,2) DEFAULT 0.00,
    wholesale_price DECIMAL(12,2) DEFAULT 0.00,
    retail_price DECIMAL(12,2) DEFAULT 0.00,
    subtotal DECIMAL(12,2) DEFAULT 0.00,
    discount_percent DECIMAL(5,2) DEFAULT 0.00,
    discount_amount DECIMAL(12,2) DEFAULT 0.00,
    discount_type VARCHAR(30),
    tax_rate DECIMAL(5,2) DEFAULT 0.00,
    tax_amount DECIMAL(12,2) DEFAULT 0.00,
    tax_exempt BOOLEAN DEFAULT FALSE,
    vat_rate DECIMAL(5,2) DEFAULT 0.00,
    vat_amount DECIMAL(12,2) DEFAULT 0.00,
    shipping_cost DECIMAL(10,2) DEFAULT 0.00,
    handling_fee DECIMAL(10,2) DEFAULT 0.00,
    insurance_cost DECIMAL(10,2) DEFAULT 0.00,
    customs_duty DECIMAL(10,2) DEFAULT 0.00,
    other_charges DECIMAL(10,2) DEFAULT 0.00,
    total_amount DECIMAL(12,2) DEFAULT 0.00,
    currency VARCHAR(10) DEFAULT 'USD',
    exchange_rate DECIMAL(10,6) DEFAULT 1.000000,
    profit_margin DECIMAL(5,2),
    commission_amount DECIMAL(10,2),
    gross_profit DECIMAL(12,2),
    
    -- Payment Information (15 columns)
    payment_terms VARCHAR(50),
    payment_method VARCHAR(50),
    payment_status VARCHAR(30),
    payment_date DATE,
    payment_due_date DATE,
    payment_reference VARCHAR(100),
    transaction_id VARCHAR(100),
    credit_card_type VARCHAR(30),
    credit_card_last4 VARCHAR(4),
    bank_name VARCHAR(100),
    check_number VARCHAR(50),
    credit_limit DECIMAL(12,2) DEFAULT 0.00,
    credit_used DECIMAL(12,2) DEFAULT 0.00,
    balance_due DECIMAL(12,2) DEFAULT 0.00,
    advance_payment DECIMAL(12,2) DEFAULT 0.00,
    
    -- Shipping Address (15 columns)
    shipping_address_line1 VARCHAR(200),
    shipping_address_line2 VARCHAR(200),
    shipping_address_line3 VARCHAR(200),
    shipping_city VARCHAR(100),
    shipping_state VARCHAR(100),
    shipping_zipcode VARCHAR(20),
    shipping_country VARCHAR(100),
    shipping_county VARCHAR(100),
    shipping_district VARCHAR(100),
    shipping_landmark VARCHAR(200),
    shipping_contact VARCHAR(100),
    shipping_phone VARCHAR(20),
    shipping_email VARCHAR(100),
    shipping_instructions TEXT,
    delivery_instructions TEXT,
    
    -- Billing Address (10 columns)
    billing_address_line1 VARCHAR(200),
    billing_address_line2 VARCHAR(200),
    billing_city VARCHAR(100),
    billing_state VARCHAR(100),
    billing_zipcode VARCHAR(20),
    billing_country VARCHAR(100),
    billing_contact VARCHAR(100),
    billing_phone VARCHAR(20),
    billing_email VARCHAR(100),
    same_as_shipping BOOLEAN DEFAULT TRUE,
    
    -- Shipping & Delivery (20 columns)
    carrier VARCHAR(100),
    carrier_service VARCHAR(100),
    tracking_number VARCHAR(100),
    tracking_url VARCHAR(500),
    shipping_method VARCHAR(50),
    service_level VARCHAR(50),
    delivery_date DATE,
    delivery_time TIME,
    delivery_window_start TIME,
    delivery_window_end TIME,
    signature_required BOOLEAN DEFAULT FALSE,
    signature_obtained VARCHAR(100),
    delivery_proof VARCHAR(200),
    package_weight DECIMAL(10,2),
    package_dimensions VARCHAR(50),
    number_of_packages INT DEFAULT 1,
    package_type VARCHAR(50),
    pallet_count INT DEFAULT 0,
    container_number VARCHAR(50),
    freight_class VARCHAR(20),
    
    -- Warehouse & Dispatch (15 columns)
    warehouse_id VARCHAR(50),
    warehouse_name VARCHAR(100),
    warehouse_location VARCHAR(200),
    dispatch_date DATE,
    dispatch_time TIME,
    dispatcher_name VARCHAR(100),
    dispatch_status VARCHAR(30),
    pick_date DATE,
    pick_time TIME,
    picker_name VARCHAR(100),
    pack_date DATE,
    pack_time TIME,
    packer_name VARCHAR(100),
    loading_dock VARCHAR(50),
    manifest_number VARCHAR(100),
    
    -- Vehicle & Driver (10 columns)
    vehicle_id VARCHAR(50),
    vehicle_type VARCHAR(50),
    vehicle_number VARCHAR(50),
    driver_name VARCHAR(100),
    driver_license VARCHAR(50),
    driver_phone VARCHAR(20),
    driver_email VARCHAR(100),
    route_plan TEXT,
    estimated_arrival DATETIME,
    actual_arrival DATETIME,
    
    -- Quality & Compliance (12 columns)
    quality_check BOOLEAN DEFAULT FALSE,
    qc_inspector VARCHAR(100),
    qc_date DATE,
    qc_status VARCHAR(30),
    qc_notes TEXT,
    safety_rating VARCHAR(10),
    compliance_cert VARCHAR(100),
    hazmat_class VARCHAR(50),
    special_handling VARCHAR(200),
    temperature_controlled BOOLEAN DEFAULT FALSE,
    temperature_range VARCHAR(50),
    regulatory_compliance TEXT,
    
    -- Returns & Refunds (10 columns)
    return_eligible BOOLEAN DEFAULT TRUE,
    return_window_days INT DEFAULT 30,
    return_reason TEXT,
    return_status VARCHAR(30),
    return_date DATE,
    rma_number VARCHAR(50),
    refund_amount DECIMAL(10,2) DEFAULT 0.00,
    refund_status VARCHAR(30),
    refund_date DATE,
    restocking_fee DECIMAL(10,2) DEFAULT 0.00,
    
    -- Customer Service (15 columns)
    csr_assigned VARCHAR(100),
    support_ticket VARCHAR(50),
    complaint_type VARCHAR(100),
    complaint_description TEXT,
    resolution_status VARCHAR(30),
    resolution_date DATE,
    resolution_notes TEXT,
    escalation_level INT DEFAULT 0,
    escalated_to VARCHAR(100),
    follow_up_date DATE,
    follow_up_required BOOLEAN DEFAULT FALSE,
    customer_feedback TEXT,
    customer_rating_service INT,
    nps_score INT,
    satisfaction_score INT,
    
    -- Warranty & Service (8 columns)
    warranty_period VARCHAR(50),
    warranty_start_date DATE,
    warranty_end_date DATE,
    warranty_claim BOOLEAN DEFAULT FALSE,
    warranty_claim_number VARCHAR(50),
    service_contract BOOLEAN DEFAULT FALSE,
    installation_required BOOLEAN DEFAULT FALSE,
    installation_date DATE,
    
    -- Notifications & Communications (8 columns)
    email_sent BOOLEAN DEFAULT FALSE,
    sms_sent BOOLEAN DEFAULT FALSE,
    notification_sent BOOLEAN DEFAULT FALSE,
    confirmation_email_sent BOOLEAN DEFAULT FALSE,
    shipping_notification_sent BOOLEAN DEFAULT FALSE,
    delivery_notification_sent BOOLEAN DEFAULT FALSE,
    notification_preferences TEXT,
    communication_log TEXT,
    
    -- Analytics & Tracking (10 columns)
    conversion_source VARCHAR(100),
    landing_page VARCHAR(500),
    session_id VARCHAR(100),
    user_agent TEXT,
    ip_address VARCHAR(50),
    device_type VARCHAR(50),
    browser VARCHAR(50),
    operating_system VARCHAR(50),
    geolocation VARCHAR(200),
    ab_test_variant VARCHAR(50),
    
    -- Performance Metrics (8 columns)
    processing_time_minutes INT,
    fulfillment_time_hours INT,
    delivery_time_days INT,
    cycle_time_total_hours INT,
    on_time_delivery BOOLEAN,
    perfect_order BOOLEAN,
    order_accuracy_score DECIMAL(5,2),
    fulfillment_accuracy DECIMAL(5,2),
    
    -- Custom Fields (20 columns)
    custom_field_1 VARCHAR(200),
    custom_field_2 VARCHAR(200),
    custom_field_3 VARCHAR(200),
    custom_field_4 VARCHAR(200),
    custom_field_5 VARCHAR(200),
    custom_field_6 VARCHAR(200),
    custom_field_7 VARCHAR(200),
    custom_field_8 VARCHAR(200),
    custom_field_9 VARCHAR(200),
    custom_field_10 VARCHAR(200),
    custom_text_1 TEXT,
    custom_text_2 TEXT,
    custom_text_3 TEXT,
    custom_number_1 DECIMAL(15,4),
    custom_number_2 DECIMAL(15,4),
    custom_number_3 DECIMAL(15,4),
    custom_date_1 DATE,
    custom_date_2 DATE,
    custom_boolean_1 BOOLEAN,
    custom_boolean_2 BOOLEAN,
    
    -- System Fields (10 columns)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    updated_by VARCHAR(100),
    deleted_at TIMESTAMP NULL,
    deleted_by VARCHAR(100),
    is_deleted BOOLEAN DEFAULT FALSE,
    version INT DEFAULT 1,
    last_modified_by VARCHAR(100),
    modification_notes TEXT,
    
    -- Indexes for Performance
    INDEX idx_order_status (order_status),
    INDEX idx_priority_level (priority_level),
    INDEX idx_customer_id (customer_id),
    INDEX idx_order_date (order_date),
    INDEX idx_delivery_date (delivery_date),
    INDEX idx_tracking_number (tracking_number),
    INDEX idx_customer_name (customer_name),
    INDEX idx_product_id (product_id),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_carrier (carrier),
    INDEX idx_sales_channel (sales_channel),
    INDEX idx_payment_status (payment_status),
    INDEX idx_shipping_city (shipping_city),
    INDEX idx_shipping_state (shipping_state),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;