-- create_database.sql  —  PostgreSQL schema
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) UNIQUE,
    role VARCHAR(20) DEFAULT 'user',
    full_name VARCHAR(100),
    phone VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customers (
    id SERIAL PRIMARY KEY,
    customer_id VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    phone VARCHAR(20),
    company VARCHAR(100),
    address_line1 VARCHAR(200),
    address_line2 VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(50),
    zipcode VARCHAR(20),
    country VARCHAR(50) DEFAULT 'India',
    customer_type VARCHAR(20),
    credit_limit NUMERIC(12,2) DEFAULT 0,
    outstanding_balance NUMERIC(12,2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    product_id VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(100),
    brand VARCHAR(100),
    sku VARCHAR(100) UNIQUE,
    description TEXT,
    unit_price NUMERIC(12,2) DEFAULT 0,
    cost_price NUMERIC(12,2) DEFAULT 0,
    stock_quantity INTEGER DEFAULT 0,
    reorder_level INTEGER DEFAULT 10,
    supplier_id VARCHAR(50),
    warehouse_location VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS warehouses (
    id SERIAL PRIMARY KEY,
    warehouse_id VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(50),
    manager_name VARCHAR(100),
    capacity INTEGER DEFAULT 0,
    current_stock INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS shipments (
    id SERIAL PRIMARY KEY,
    shipment_id VARCHAR(50) UNIQUE NOT NULL,
    order_id VARCHAR(50),
    carrier VARCHAR(100),
    tracking_number VARCHAR(100),
    ship_date DATE,
    delivery_date DATE,
    status VARCHAR(30),
    origin VARCHAR(200),
    destination VARCHAR(200),
    weight NUMERIC(10,2),
    shipping_cost NUMERIC(10,2),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    order_id VARCHAR(50) PRIMARY KEY,
    customer_id VARCHAR(50),
    customer_name VARCHAR(100),
    customer_email VARCHAR(100),
    customer_phone VARCHAR(20),
    customer_company VARCHAR(150),
    customer_type VARCHAR(30),
    customer_segment VARCHAR(50),
    customer_tier VARCHAR(20),
    customer_since DATE,
    customer_rating NUMERIC(3,2),
    customer_lifetime_value NUMERIC(12,2),
    account_manager VARCHAR(100),
    customer_city VARCHAR(100),
    customer_state VARCHAR(50),
    customer_country VARCHAR(50),
    order_date DATE,
    order_time TIME,
    order_status VARCHAR(30) DEFAULT 'Pending',
    priority_level VARCHAR(20) DEFAULT 'Medium',
    order_type VARCHAR(50),
    sales_channel VARCHAR(50),
    sales_rep VARCHAR(100),
    department VARCHAR(50),
    region VARCHAR(50),
    division VARCHAR(50),
    product_id VARCHAR(50),
    product_name VARCHAR(200),
    product_category VARCHAR(100),
    product_subcategory VARCHAR(100),
    brand VARCHAR(100),
    model VARCHAR(100),
    sku VARCHAR(100),
    quantity INTEGER DEFAULT 1,
    unit_price NUMERIC(12,2) DEFAULT 0,
    subtotal NUMERIC(12,2) DEFAULT 0,
    discount_percent NUMERIC(5,2) DEFAULT 0,
    discount_amount NUMERIC(12,2) DEFAULT 0,
    tax_rate NUMERIC(5,2) DEFAULT 0,
    tax_amount NUMERIC(12,2) DEFAULT 0,
    shipping_cost NUMERIC(10,2) DEFAULT 0,
    total_amount NUMERIC(12,2) DEFAULT 0,
    currency VARCHAR(10) DEFAULT 'INR',
    payment_status VARCHAR(30),
    payment_method VARCHAR(50),
    payment_due_date DATE,
    shipping_address_line1 VARCHAR(200),
    shipping_address_line2 VARCHAR(200),
    shipping_city VARCHAR(100),
    shipping_state VARCHAR(100),
    shipping_country VARCHAR(100),
    shipping_zipcode VARCHAR(20),
    carrier VARCHAR(100),
    tracking_number VARCHAR(100),
    delivery_date DATE,
    delivery_status VARCHAR(30),
    warehouse_id VARCHAR(50),
    warehouse_name VARCHAR(100),
    dispatch_date DATE,
    driver_name VARCHAR(100),
    vehicle_number VARCHAR(50),
    marketing_campaign VARCHAR(100),
    utm_source VARCHAR(100),
    region_name VARCHAR(100),
    return_status VARCHAR(30),
    qc_status VARCHAR(30),
    on_time_delivery BOOLEAN,
    perfect_order BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_status_date ON orders(order_status, order_date);
CREATE INDEX IF NOT EXISTS idx_orders_city_state ON orders(shipping_city, shipping_state);
CREATE INDEX IF NOT EXISTS idx_orders_customer_city ON orders(customer_name, customer_city);
